# [general]
title = "Test"
description = "This is a test"
type = "Event"

test1 = 1
test2 = { 
    test = 1, test1 = "test reussi"
}
test3 = [ 1, 2, "test", 2.3 ]
test4 = """\
    ceci est un test
    ceci est un test"""
